---
title: "Stability and resilience of ecological networks"
author: "Fernando Cagua"
date: "`r format(Sys.Date(), '%B %Y')`"
output: 
  pdf_document:
    includes:
      in_header: header.tex
    toc: no
    fig_caption: yes
    number_sections: no
bibliography: ../references.bib
biblatex: yes
documentclass: book
---
---
geometry: a4paper
geometry: showframe
geometry: margin=1in
geometry: bindingoffset=0in
geometry: twoside=FALSE
---

```{r libraries, echo = FALSE, message = FALSE}
library(ggdendro)
library(ape)
library(magrittr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(grid)
source("./code/multiplot.R")
```

\newgeometry{right=3in, twoside=FALSE}

\chapter*{Introduction}
\addcontentsline{toc}{chapter}{Introduction}

Species in a ecological community form networks of interactions that determine the functioning of the ecosystem. Chiefly, interactions can be antagonistic ---like those between hosts and parasites or plant and herbivores--- or mutualistic ---like those between plants and pollinators or coral and their symbiotic algae. 

Anthropogenic pressures are a major driver of ecosystem change [@Large2015]. The way ecosystems respond to those drivers is largely determined by the structure or their interaction networks. Because ecosystem interactions are of tremendous importance for global biogeochemical cycles, ecosystem services, and the maintenance of global biodiversity, understanding the implications of network structure for ecosystem response is paramount.

For my dissertation I propose to study the role of species' interactions on the response of ecosystems to drivers of change. Specifically I aim to build a general understanding of how network structure and species coexistence interplays with the ecosystem's stability, resilience and adaptive capacity. 

These three concepts ---introduced by Holling [-@Holling1973] and later reviewed by Gunderson [-@Gunderson2000]--- have been key in quantifying the dynamics and behaviour of ecosystems. **Stability** describes the property of a system to return to an equilibrium point after disturbance. On the other hand **Resilience** is a meassure of stability that mediates transitions between ecosystem stable states; it is defined by "the amount of disturbance that an ecosystem could withstand without changing self-organized processes and structures" (stable states) or as "the return time to a stable state following a perturbation". In turn the **adaptive capacity** describes "the processes that modify ecological resilience".

I start by stuyding the outcome of species invasions under different structures of mutualistic networks. Species invasions are a major driver of change in many ecosystems, with important consequences on ecosystem functioning and biodiversity [@Ehrenfeld2010; @Powell2011; @Thomsen2014]. Mutuallistic networks, on the other hand, are crucial for the maintenance of global biodiversity. For instance mutuallistic networks are responsible of 90% of seed dispersal in tropical plants [@Bascompte2007] and the pollination of arround 70% of the global food crops [@Klein2007]. 

In reality ecosystems dynamics are comprised by feedbacks that include more than one type of interactions. I propose to expand the understanding of ecosystem invasibility when it includes agonistic interactions in the second chaper of my dissertation. Previous evidence shows that the network's structural patterns that promote stability vary depending on the type of interaction [@Thebault2010; @Sauve2014], but little is known about the factors that make an ecosystem more resilient against invasors and other drivers. 

Species that share similar interactions in a ecological network can be grouped in modules. Because the species's functional role in the community is, at least to a great extent, defined by its interactions [@Dehling2014], modules should implicitly group species with similar functional roles [@Dupont2009]. Functional redundancy has been proposed as an important factor in determining the ecosystem's response to disturbaces [@Brandl2014a]. For the trhid chapter, I propose to analyse the role that functional groups have in the ecosystem's resilience, and how the disruption of functional groups affects the ecosystem's adaptive capacity. 

In these first three chapters, I analise stability ignoring one important aspect: that some ecosystem stable states are more desirable than others (in terms of ecosystem services). Anthropogenic drivers or ecosystem change are multidimensional and are escalating at an alarmant rate. Understanding what causes the transition between different different ecosystem's stable states is a crucial step towards preventing undesirable transitions and restoring ecosystems that are already in an alternate undesirable state.



\iffalse


Environmental drivers to ecosystem responses. 

\chapter{Species invasions and network structure}

Species invasions, caused by successful introductions or ecosystem feedback that affect system dynamics. How they affect system stability. 

Starting with a mutualistic case-study. 

Competition introduces feedbacks in the system and non linear dynamics. 

\chapter{Stability of plant antagonistic + mutualistic networks}

asd [@Thebault2010] asd [@Sauve2014]

T. Hughes talk/

Integrating antagonistic and mutualistic, invasibility. Simulation of environmental drivers that affect ecosystems. Rather than 

\chapter{Functional redundancy and network resilience}

From an individual perspective to a group perspective. 

\chapter*{Timeline}
\addcontentsline{toc}{chapter}{Timeline}

\chapter{Pet projects}

# Global biogeographic patterns of plants and pollinators

# Biogeography and phylogenies: evolutionary patterns of tropical coral reefs and fishes

# Effect of coevolution on network stability

\fi
\newgeometry{margin=1in, twoside=FALSE}
\chapter*{References}
\addcontentsline{toc}{chapter}{References}







