---
title: "Find a good title..."
author: "Fernando Cagua"
classoption: a4paper
output: pdf_document
csl: nature.csl
bibliography: ../../references.bib
---
---
geometry: a4paper
---
\vfill
\begin{center}
\subsubsection{Research Summary}
\end{center}

Natural ecosystems provide important services---like food and water---that we humans depend on to a large extent.
Much like the failure of a single key financial institution can trigger unexpected crashes on the stock market, human pressures---such as biological invasions and species extinctions---can cause sudden collapses that severely transform the way ecosystems function.
However, despite its importance, we do not completely understand the dynamics that make ecosystems resilient to such collapses.
Because the functioning of ecosystems is largely determined by the network of interactions between the species that inhabit them, my proposed research aims to quantify the role played by species interactions in determining the resilience of ecosystems.
To achieve this, I will focus on networks of mutually beneficial interactions, like those between plants and their pollinators, and use a combination of empirical data, computer simulations and ecological theory.
Ultimately I want to better understand why, when and how ecosystem collapses occur, and how to best recover from them.

\vfill
\vfill
\vfill

\subsubsection{Titles}

Anticipating and managing ecosystem collapses

Understanding ecosystem collapses

How do species interactions regulate ecosystem collapses?

How do species interactions determine ecosystem collapses?

Ecosystem collapses are regulated by species interactions

How are ecosystem collapeses regulated by species interactions

Ecosystem responses to drivers of global change

Building resilience: how do species interactions regulate ecosystem collapses?

Insuring ecosystem services: how do species interactions regulate ecosystem collapses?

Salvaging ecosystem services: how do species interactions regulate ecosystem collapses?

Salvaging ecosystem services: how do ecological networks regulate ecosystem collapses?

\vfill

\newpage

## Research Proposal

From food and freshwater production to recreation and carbon sequestration, ecosystems provide a wide range of services of considerable value to humans.
Unfortunately, the frequency of undesired ecosystem collapses---like the (often sudden) shift from a transparent to a turbid lake or from a self-sustaining fishery to a collapsed one---is dramatically increasing worldwide[@Scheffer2001a].
When ecosystem resilience is limited, breakdowns are more likely, and their ability to provide those services we depend on is endangered.
Therefore, a necessary step to anticipate, prevent, and reverse ecosystem collapse is to understand the processes that support, or undermine, ecosystem resilience [@Hughes2005; @Tylianakis2008].

Resilience is related to the amount of disturbance that an ecosystem could withstand without collapsing, or, in ecological jargon, without undergoing a regime shift---a large, persistent transformation in ecosystem functioning and structure [@Holling1973; @Gunderson2000].
Moreover, substantial research indicates that ecosystem functioning and structure are strongly influenced by the network of interactions formed by species in an ecological community [@Bascompte2006; @Dobson2006; @Tylianakis2008; @Reiss2009].
Since these factors ultimately determine ecosystem's response to disturbances, **the overall objective of my proposed research is to quantify the role played by species interactions in modulating ecosystem resilience**.

Because of their importance for food production and the maintenance of global biodiversity [@Bascompte2006; @Bascompte2007; @Klein2007], I will focus on networks of mutualistic interactions between plants and pollinators.
Despite their significance, we do not know how vulnerable pollination systems are to biotic invasions---an important component of human-caused global change [@Vitousek1997].
**The first objective of my research is therefore to determine how the properties of a network determine the susceptibility and resilience of an ecosystem to biotic invasions**.
Ecosystem pressures, however, rarely act in isolation.
It has been shown that biotic invasions often occur in ecosystems that have already been degraded by species removal [@Bennett2015].
**My second objective is to determine the compound effect of biodiversity loss and invasive species on the resilience of an ecosystem**.
To answer these questions, I will use a combination of previously collected empirical data [@Bartomeus2008], complex-network theory [@Strogatz2001; @Newman2003], and computer simulations of the species' population dynamics in the community [@Bastolla2009; @Garcia-Algarra2013].
In particular, I will contrast the structural (complex networks) and dynamical (population models) properties of real and simulated ecosystems under different invasion/defaunation conditions [@Romanuk2009; @Rohr2014; @Tylianakis2014], and evaluate their effects on ecosystem resilience.

The first two objectives of my thesis are designed to answer underlying questions of resilience theory; however, **my third objective is to translate the gained insight into useful lessons for ecosystem management**.
Ecosystems are complex, non-linear systems that are very difficult to control.
Nevertheless, recent work in theoretical physics has highlighted that is indeed possible to regulate them using targeted interventions [@Cornelius2013].
I propose to build upon these findings to determine the optimal set of species---from a feasibility and effectiveness perspective---that are required to modify an ecosystem state.
Rescuing ecosystems from the brink of collapse and recovering them from undesired shifts is a major goal in conservation science.
Finding a way in which actions targeted to specific species can maximise the ecosystem resilience will bring us much closer to achieving that goal.

My main personal and profesional goal is to gain a deeper understanding, and ultimately improve the management, of the ecosystems I love.
Despite the quantitative insight I gained as an engineer, my scientific career in biology, both in academia and the non-for-profit sector, has been largely centered on taking an empirical approach to conservation ecology.
However, over the last years, I have discovered the need to also incorporate fundamental ecological theory.
My proposed research is heavily influenced by this realisation.
In a world of constant change, building resilience is our best insurance against losing the ecosystem services we value and depend on.


\newpage

## Impact Statement

About two thirds of New Zealand plants are pollinated by birds or insects[@Cox2000];.
this includes iconic native plants (like kowhai and pohutukawa), and economically important crops (like kiwifruit, apples and grapes).
The historical depletion of native birds [@Anderson2003; @Robertson2009] provides a prime example of how pollination systems in New Zealand are losing key pollinators, plants and habitats[@Cox2000].
At the same time pollination systems are being disrupted by naturalised or invasive species [@Cox2000]; for instance, 50% of plant species in New Zealand are introduced[@Wilton2000], and imported social bees are now an important component of pollinator fauna [@Lloyd1985; @Newstrom2005].
In combination with low levels of pollinator diversity, that makes New Zealand flora particularly vulnerable to declines in pollination services [@Newstrom2005; @Cox2000].
Also, in contrast with other locations, pollination networks in New Zealand are dominated by generalist species[@Heine1937; @Primack1983]---plants that attract a wide range of pollinator species, and pollinators that visit a wide range of plants.
My proposed PhD will help understand how these differences affect the resilience of New Zealand's pollination systems, especially when considering that ecosystems have already been changed both by extinctions and invasive species.

My PhD will take place in [Dr. Daniel Stouffer's lab](http://www.stoufferlab.org/) at the University of Canterbury.
Dr. Stouffer is a Rutherford Discovery Fellow whose interdisciplinary research group focuses on cutting-edge research on ecological complexity, is quite visible internationally, collaborates widely, and regularly receives visiting scientists from several countries.
The theoretical and quantitative tool set I will gain under his supervision is an excellent complement to my professional background, and I have no doubt it will be key for the success of my future research career.
Also, my proposed project aligns nicely with the interests of some highly cited researchers with whom collaborations might naturally emerge: [Jason Tylianakis](http://www.tylianakislab.org/) (University of Canterbury), [Jordi Bascompte](http://www.bascompte.net/) (University of Zurich), [Martin Scheffer](http://www.sparcs-center.org/) (Wagenigen University), and [Carl Folke](http://www.stockholmresilience.org/21/contact/staff/1-15-2008-folke.html) (Stockholm Resilience Center). As such, I expect there to be a widespread international interest in the scientific outcomes of my research.

Understanding how invasions interact with defaunation in ecological networks is therefore both a global research priority and essential for conserving, restoring, and managing New Zealand ecosystems [@Newstrom2005].First, mutualistic plant-pollinator networks are pivotal for the maintenance of biodiversity and crop production [@Bascompte2007; @Klein2007].
Second, biotic invasions and defaunation are critical components of human-caused global change that have a planetary reach, but from which New Zealand has particularly suffered, and remains notably vulnerable [@Vitousek1997].

The results of my research will also have direct application to ecosystem management, and subsequent clear conservation benefits for ecosystems in New Zealand and elsewhere.
For example, the introduction, and subsequent invasion, of stoats in New Zealand was an expensive mistake in which species interactions were not taken into account [@Kuiti1992; @Thomson2011].
Moreover, although we have identifed the effects of this invasion on some iconic native species [@Brown1993; @McLennan1996], we currently do not understand how the changes to ecosystem dynamics are affecting the resilience of the ecosystems as a whole.
The research I propose intends to establish the general theory necessary to answer this question.
Doing so is especially important when the ecosystem response might be inconspicuous until transformation is imminent [@Lever2014; @Tylianakis2014].
Only by better understanding the dynamics behind species interactions can we hopefully be better prepared to anticipate, prevent and reverse undesired ecosystem collapses.

\newpage

## References
