---
title: 'Proposal - Ecosystem responses to escalating drivers: linking species interactions
  and resilience'
author: "Fernando Cagua"
csl: ../nature.csl
output: pdf_document
bibliography: ../../references.bib
---

---
geometry: a4paper
---
\iffalse
\begin{center}
\subsubsection{Research Proposal - New Zealand International Doctoral Research Scholarship}
\end{center}
\fi

The intensity of human generated drivers---climate change, land use, defaunation, nutrient enrichment, and biotic invasions---is increassing, and the trend is likely to continue [@Hughes2013a]. Those drivers are heavily modifying the functioning of many of the ecosystems we depend on [@Large2015]. On the other hand, species in an ecological community form an network of interactions of tremendous importance for example, for the provision of ecosystem functioning, the provision of services, the maintenance of global biodiversity, and biogeochemical cycles [@DeAngelis1992; @Bascompte2006; @Dobson2006; @Reiss2009]. 

The overall objective of my proposed research is to improve our current understanding of the ecosystems response to multiple anthopogenic drivers and their cummulative impacts. In particular, I will focus on the role that networks of species interactions have in modulating the resilience of ecosystems---the amount of disturbance a system can withstand without entering a regime shift [@Holling1973].

Regime shifts are large, persistent changes in the function and structure of the ecosystem [@Gunderson2000]---like the (often sudden) shift from a transparent to a turbid lake, from a woodland to a grassy landscape, from a self-sustaining fishery to a collapsed one, or from a coral dominated reef to one dominated by algae [@Scheffer2001a]. A neccessary step to anticipate, prevent and reverse unwanted regime shifts caused by drivers of environmental change, is to understand the processes that support or undermine resilience and the role played by species interactions [@Hughes2005; @Tylianakis2008]. 

Despite the fact that the effect of those drivers permeates across entire communities, our understanding of their impacts is mostly based on studies of one or a few species. For my research I will use a complex network approach, which recognises that species live within a comminity, and that they interact between them. This approach---built upon tools from statistical physics and the social sciences---has been key in revealing structural patterns that trascend specific ecosystems [@Williams2000; @Dunne2002; @Stouffer2005a]. Using a combination of complex system theory, population models, resilience theory and previoulsy published empirical data I aim to untangle the mechanisms that link species interactions with the ecosystem's resilience to environmental drivers of change. 

As a model system, I will use mutuallistic plant-pollinator networks, which are critical for global food production and biodiversity maintenance [@Bascompte2007; @Klein2007]. Initially I will use biotic invasions as the environmental driver. Because of the paucity of empirical observations of network dynamics subject to invasions, I will simmulate community-wide interspecies coexistence dynamics, and explicitly quantify the stability of the system from population fluctuations [@Bastolla2009; @Garcia-Algarra2013]. This approach will enable me to predict how the structural and dynamic characteristics of the network determine the "invasibility" of an ecosystem, and when invasions are likely to lead to a regime shift [@Romanuk2009; @Rohr2014]. 

Biotic invasions often act over ecosystems that are already degraded [@Bennett2015]. Using a similar methodology as for the species invasions, I will follow by styding how defaunation---from a functional perspective---affect the pre-invasion ecosystem resilience. Although some species (like beavers for example) are functionally unique in the ecosystem, some others are redundant in that they contribute in similar ways to an ecosystem fucntion [@Naeem1998]. Despite theoretical and empirical evidence showing that the degree of functional redundancy has major effects on ecosystem stability and species coexistence [@Walker1999; @Fonseca2001; @Bellwood2003b; @Loreau2004; @Allison2008; @Brandl2014a], we still don't know how diversity witin functional groups maps into different stability domains in the ecosystem [@Rohr2014].

The final objective of my proposed research is to translate the gained insight into useful lessons for ecosystem management. Recent work has highlighted that in theory it is possible to control a complex network, by inducing compensatory perturbations [@Cornelius2013], but this approach has never been used in ecology. I propose to expand this method to find the minimum number of species that have to be directly managed to move the ecosystem from one state to another, or to rescue one at the bring of failure. I will use empirical and simulated networks from ecosystems that have undergone a regime shift  

Over the last years I have been focused on studying the ecology of tropical marine organisms. Through my previous research I have withnessed how entire ecosystems transform due to human pressures. Understanding what makes ecosystems vulnerable, and how to prevent and revert those undersirable transformations---not only on marine ecosystems---became my top scientific interest; I want to answer fundamental questions in ecology and ultimately improve the management of the ecosystems I love. I am aware long term goal that is likely to guide my scientific career for the next decade. My proposed PhD research, and the support from the NZIDRS, are going to be instrumental to reach those goals.

### References

\iffalse

Funder guidelines:

* Your proposal should be thoroughly researched, well thought out, feasible, and clearly articulated
* Your proposal should identify specific areas of study and outline methodology
* Include an assessment of the benefits (both professional and personal) that you expect from your proposed research

Considerations:

1. Hook attention from the get go
2. Make sure it fits what they want
3. Audience = no idea about anthing
4. I matter. Sell myself. Carrer highlights and contributions to date
5. Good title. Grandma should understand it, avoid questions, short and to the point, tell why is so bloody important
6. Tell. What I'm gonna do. WHy is so exciting. What will it solve
7. Tell inmediatelly what I'm intending to reseracg. An assessor wants to see that you’ll be proposing to do x, y and z such that you can answer big questions a, b and c efficiently, effectively and convincingly.
8. Convince it's exciting. Make anyone who read it excited
9. Explain applied outcomes. how your results will affect the real world, either through policy, technology or remediation
10. State hypothesis and predictions and how to test them. Be realistic about them
11. Methodologically specific. 
12. Communication strategy. Reaches for the public with clever and inovative ways

\fi