---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Effect of environment on networks {#sdm-networks}

\begin{flushright}{\slshape
    Stare at the world, \\
    not at your model.} \\ \medskip
    --- \textcite{kling_practitioners_2007}
\end{flushright}


## Introduction

```{r fig-distribution-species-mult-locations, fig.height = 2.2, fig.cap = "Frequency distribution of the number of locations in which a species is present. The most common pollinator species was emph{Apis melifera}, which was sampled on 42 locations, while the most common plant species was emph{Trifolium repens}, which was sampled on 11 locations", fig.scap="Location dstribution of species.", out.extra=''}

dist_species_multiple_locations_data <- readRDS("data/sdm_networks/species_location_distribution.rds")

# pdf(width = fig_sizes()$two_column_width, height = 2.4)
plot_species_location_distribution(dist_species_multiple_locations_data)
# dev.off()
```



```{r fig-sensitivity-analysis, fig.height = 2.2, fig.cap = "Sensitivity analysis of environmental stress error. The number of independent occurrences retrieved from GBIF is inversely related to the error of bioclimatic suitability for our plant-pollinator networks. The sensitivity analysis was performed by subsampling occurrences of emph{Archilochus colubris}, the species in our dataset with the largest number of occurrences in GBIF, which was recorded in two of our communities.", out.extra='', fig.scap="Sensitivity analysis of environmental stress error."}


fig_sensitivity_analysis_data <- readRDS("data/sdm_networks/fig_sensitivity_analysis_data.rds")

plot_sensitivity_analysis(fig_sensitivity_analysis_data)
```


```{r fig-conditional-effects, fig.height = 2.2*1.75, fig.cap = "Conditional effects of predictors in our baseline model. The shown values are based on predictions for a hypothetical community with 76 and 33 pollinators. These values correspond to the median number of species in each guild across communities. In each panel, we condition on the mean value of the other predictor in the model. We indicate mean values for each predictor with a vertical dashed line. For model fitting, we scaled all predictors to have a mean of zero and unit variance; however, here we show the unscaled predictors to facilitate interpretation. To illustrate the uncertainty around the fitted estimates, we plot the fits of 100 independent draws from the posterior distribution. The thick lines indicate the mean values of the response distribution. As there was no interaction between the guild and the number of possible interactions, we only show the conditional effect of pollinators."}

fig_conditional_effects_data <- readRDS("data/sdm_networks/fig_conditional_effects_data.rds")

plot_all_conditional_effect(fig_conditional_effects_data)
```

*asd*

```{r tab-model-comparison}
model_ranking <- readRDS("data/sdm_networks/model_ranking.rds")

model_ranking$waic %>%
  purrr::map(~.$estimates["waic", ]) %>% 
  purrr::map_df(~tibble::tibble(estimate = .[1], se = .[2]), .id = "formula") %>%
  dplyr::arrange(estimate) %>%
  dplyr::filter(formula != "formula_full") %>%
  dplyr::mutate(formula = translate_model_formula(formula, "long-abv"), 
                formula = kableExtra::cell_spec(formula, format = "latex", 
                                                bold =nchar(formula) == max(nchar(formula)))) %>% 
  knitr::kable("latex", 
               booktabs = TRUE, 
               digits = c(0,0,0), 
               format.args = list(big.mark = ","), 
               col.names = c("predictors", "WAIC", "SE"),
               escape = FALSE,
               linesep = "",
               caption = "Comparison in out of sample predictive power of the baseline model (bold) and their alternatives. We rank models by their expected log predictive density based on their Wanatabe-Akaike information criterion (WAIC).") %>%
  kableExtra::kable_styling(font_size = 10) #%>%
```