# The pollination trade off

\begin{flushright}{\slshape 
    Los animales todos, en suma, no pueden pasarse sin alimento.
    El animal cazador no puede tampoco escapar de ser, a su vez, cazado.
    Todo animal debil devora al que es mas debil que el. Todo animal fuerte, no puede librarse de ser devorado por otro animal mas fuerte que el. Y en esto son exactamente igual los hombres, unos respecto de otros, aunque no lieguen a los mismos extremos. Dios, en suma, ha puesto a unos seres como causa de la vida de otros, y reciprocamente a estos como causa de la muerte de aquellos.  } \\ \medskip
    --- al-Jāḥiẓ, \\ translated by \textcite{palacios_libro_1930}
\end{flushright}

## Summary {-}

A fundamental feature of pollination systems is the indirect facilitation and competition that arises when plants species share pollinators. 
When plants share pollinators, the pollination service can be influenced. 
This depends not only on how many partners plant species share, but also by multiple intertwined factors like the plant species' abundance, visitation, or traits. 
These factors inherently operate at the community level. 
However, most of our understanding of how these factors may affect the pollination service is based on systems of up to a handful of species. 
By examining comprehensive empirical data in eleven natural communities, we show here that the pollination service is—surprisingly—only partially influenced by the number of shared pollinators. 
Instead, the factors that most influence the pollination service (abundance and visit effectiveness) also introduce a trade-off between the absolute amount of conspecific pollen received and the amount relative to heterospecific pollen. 
Importantly, the ways plants appear to balance these trade-offs depend strongly on the community context, as most species showed flexibility in the strategy they used to cope with competition for pollination. 

## Introduction

Animal pollination plays a disproportionally important role in food production and maintenance of global biodiversity [@bascompte_plant-animal_2007; @klein_importance_2007; @ollerton_how_2011]. 
At a pairwise level, the mutually beneficial relationship between plants and pollinators underpins the pollination service. 
At a community level, sometimes involving hundreds of species, both plant and pollinator species are connected in a myriad of indirect connections when pollination partners are shared. 
These indirect connections can dramatically alter the quality of the pollination service that plants receive because they determine how conspecific and heterospecific pollen is transferred across the community [@morales_interspecific_2008]. 
Generally speaking, there is a trade-off between the benefits gained from a species maximising its number of partners and the costs of sharing them with other plant species [@waser_interspecific_1978].
However, due to the large number of factors that operate at the community level, we generally do not know how sharing pollinators affects the pollination service beyond systems with more than a handful of species. 
Here we investigate how pollinator sharing affects pollen transfer *in natural communities* and how it compares to other factors known to play a role in community dynamics like abundance, traits, and visitation patterns.

There are two main mechanisms through which sharing pollinators can affect plant fertilisation [@morales_interspecific_2008]. 
The first is by changes in intraspecific pollen transfer.
Changes in intraspecific pollen transfer happen, for example, when plants with more attractive flowers might reduce the number of visits to those less attractive neighbouring plants, and hence reduce the amount of *conspecific pollen* deposited by animals [@yang_pollinator_2011]. 
The second is via interspecific pollen transfer. 
In that case, even receiving a visit might not necessarily translate into fertilisation [@campbell_mechanism_1985] because a focal plant might receive *heterospecific pollen* or because pollen from the focal plant might be lost to different species. 
Naturally, the precise effects on female or male plant fitness of conspecific and heterospecific pollen deposition depend on the species involved [@arceo-gomez_invasion_2016] and are unknown for many plant species. 

Even for species well adapted to pollinator sharing, receiving foreign pollen on stigmas or losing pollen to foreign stigmas is neutral (at best). 
Indeed, there is substantial evidence supporting the idea that heterospecific pollen deposition can be detrimental to seed production and plant fitness [@ashman_toward_2013; @arceo-gomez_invasion_2016].
All else being equal, provided pollen is viable and compatible [@ramsey_pollen_2000; @de_jong_plant_1992; @dafni_pollen_2000], the higher the quantity of conspecific pollen and its purity (relative to heterospecific pollen), the better the pollination service received by the focal plant. 
As such, measuring conspecific and heterospecific pollen deposition provides a good indication of the potential levels of facilitation and competition a plant population might experience. 

By definition, intra- and interspecific pollen transfer occur at the community scale.
However, with few exceptions [@tur_evaluating_2016; @aizen_reproductive_2010], most of what we know about pollen transfer and its relationship with key ecological factors are based on studies with two plant species. 
That is partly so because the factors that determine the patterns of pollen deposition at the community scale are tightly intertwined, operate simultaneously, and may lead to emergent phenomena not observed at smaller scales [@flanagan_effects_2011].
For instance, recent empirical evidence suggests that plants with flowering traits that are "original" relative to others in the community generally have fewer interaction partners [@coux_linking_2016]. 

This evidence aligns with the notion that a species that interacts with few species does so strongly with each of them whereas a species that interacts with a large number of species does so comparatively weakly [@thebault_does_2008; @bascompte_asymmetric_2006; @vazquez_species_2007].
If evolutionary specialisation occurs by changing traits to focus on fewer but better partners [@caruso_competition_2000], we should expect a reduction of competition for pollinators in species with "original" traits and an increase of competition in species with a large number of interaction partners [@gibson_can_2012; @carvalheiro_potential_2014]. 
Alternatively, it might also be the case that abundance (for example, in terms of flower or pollen counts) is the dominant force driving pollen transfer [@seifan_outcome_2014]. 
Abundant plant species might experience a dilution of available pollinators [@feinsinger_effects_1987; @feldman_when_2004] but might also receive more effective visits by capitalising on a larger share of both visits and the pollen carried by pollinators [@stavert_plant_2019].
In this case, a potential reduction in the absolute amount of conspecific pollen received could be compensated by an increase in the amount of conspecific pollen relative to heterospecific pollen.
Altogether, it is clear that these ecological factors can indeed shape pollen deposition at the community level. 
However, we still do not understand their relative importance and *the trade-offs* that might exist between them. 

Here, we investigate pollen-deposition dynamics at the community scale using empirical data from eleven plant-pollinator communities in the Argentinian Pampas. 
First, we investigate the relative contribution that four ecological factors make to the pollination service. 
Specifically, we hypothesise that there are trade-offs on how these factors affect the quantity and purity of conspecific pollen deposition. 
While quantity and purity should decrease for plants that share many pollination partners, other factors like the plant's functional originality, its relative floral abundance, and its visitation patterns should have the potential to compensate for this decrease
Second, we examine how these four factors that might affect pollen deposition can change across communities where species are present. 
Because these factors may affect the pollination service in contrasting ways, and a species role is relative to other species in the community, we predict that species present in multiple communities should be flexible enough to compete for pollinators under different community contexts. 
