# Structural controllability

## Introduction

A major goal in ecology is to understand the roles played by different species in the biotic environment.
Within community ecology, a complex-systems approach has led to the development of a variety of analytical and simulation tools with which to compare and contrast the roles of species embedded in a network of interactions [@guimera_cartography_2005; @bascompte_assembly_2009; @stouffer_evolutionary_2012; @coux_linking_2016].
A particularly relevant dimension of any species' role is its ability to alter the abundance of other species and the state of the community—since changes of this nature can have knock-on effects on ecosystem function, diversity, processes, and services [@thompson_food_2012; @tylianakis_global_2008; @tylianakis_conservation_2010].
This ability is sometimes referred to as a species' "keystoneness" [@mills_keystone-species_1993]. 

A significant proportion of the network tools used to estimate species' roles in this context rely on the calculation of a species' centrality—a relative ranking of its positional importance that originally stems from social-network research [@noah_e._friedkin_theoretical_1991; @martin_gonzalez_centrality_2010]. 
Generally speaking, central species tend to be better connected and consequently are more likely to participate in the network's "food chains". 
Because species that participate in more chains are more likely to affect the abundances of other species, centrality metrics have often been used to identify keystone species in the community [@jordan_quantifying_2007]. 
Centrality metrics have been shown to be useful tools to rank species in regard to their potential to alter the abundances of other species, in particular when estimating the probability of secondary extinctions that may follow the loss of a species [@dunne_network_2002; @kaiser-bunbury_robustness_2010].

Despite being conceptually intuitive, the relationship between centrality and a species' presumed impact on the state of the community is largely phenomenological. 
On the one hand, substantive changes in ecosystem functioning can also occur without complete removal of a species [@mouillot_functional_2013].
On the other, we are often interested in a *specific* state of the community that might be desirable to attain (or preserve) because of its biodiversity, resilience, functioning, or the ecosystem services it provides. 
In these cases, it might be less useful to understand which species may cause *any* change in the community. 
Instead, we are better served by understanding how the structure of the network can be harnessed to achieve the desired state and which species may play the largest role in this targeted process. 
When the state of a community is underpinned by more than a single species (often the case in real communities) and we move beyond single-species removals, we might expect the accuracy of centrality to diminish.
As a result, community ecology could arguably benefit from an alternative, perhaps more mechanistically-grounded, approach to understand how species affect each other's abundance. 

Species' abundances---and consequently the state of the community as a whole---are influenced both by the structure of their interactions and the dynamics of these interactions, including the mechanisms of self-regulation [@lever_sudden_2014]. 
However, community and population dynamics can be modelled in innumerable ways, and empirical support for one versus another is often still ambiguous [@holland_population_2002]. 
The alternative approach should, therefore, ideally acknowledge ecosystem dynamics, but without being overly dependent on the particular choices of how they are characterised.
Among the various possibilities *structural controllability*, a branch of control theory, appears to be a strong candidate [@isbell_human_2013]. 
Control theory is a widely-studied branch of engineering used to determine and supervise the behaviour of dynamical systems [@motter_networkcontrology_2015]. 
It is inherently designed to deal with system feedbacks and its application has recently been expanded to complex networks [@lin_structural_1974;  @liu_control_2016]. 
Consistent with long-standing ecological questions, advances in structural controllability have established a clear link between the structure of the network and the way nodes affect each other. 
Unlike centrality indices, however, this link is not based on a priori assumptions between network metrics and keystoneness but is instead based on well-established advances in both dynamical and complex-systems theory [@motter_networkcontrology_2015].

At its fundamental level, structural controllability first determines whether a system is controllable or not; that is, it asks if a system could ever be driven to a desired state within a finite amount of time. 
Although the controllability of a network is a whole-system property, it has recently been shown that asking for the controllability of a complex-system is equivalent to finding a particular set of relevant nodes: the set with which is possible to control the state of the whole network [@liu_control_2016].
Importantly, this set of nodes is not always unique for a given network.
This implies that an examination of the distinct sets provides a means to connect nodes with their *general* ability to modify the system to which they belong.

Here, we apply methods from structural controllability to a particular ecological problem and show how it can be used to generate insight into the role of species in an ecological network. 
Specifically, we outline the approach using a set of ten pairs of uninvaded and invaded plant-pollinator communities. 
We use invaded communities because there is strong empirical evidence showing that invasive species play an important role shaping the abundances of other species, something which is particularly true in these ten networks [@lopezaraizamikel_impact_2007; @bartomeus_contrasting_2008]. 
This choice thus offers us an opportunity to explicitly contrast our theoretical observations with empirical evidence.
Moreover, empirical observations indicate that steering the state of some communities—for example during ecosystem restoration or invasive species removal—can be a very difficult task [@woodford_confronting_2016]. 
Therefore, we first ask whether there are differences between the controllability of invaded and uninvaded networks. 
We then expand existing methods from control theory to effectively link the *controllability* (Table \@ref(tab:tab-glossary)) of a network with the role of its constituent species.
We ask—from a control-theoretic perspective—whether there are key differences between species in the role they play at driving the state of the community and explore the ecological factors related to these differences. 
This allows us to identify species that might be critical for network control and show that they have a larger than expected impact on the stable coexistence of the community.
Finally, we compare the proposed approach to current methods based on species' centrality and show how these methods are indeed valuable but ultimately paint a limited picture in regard to the "keystoneness" of a species.

```{r tab-glossary}
defs <- list(
  "Network control" = "A network is said to be controllable if it is possible to steer it from an initial to an arbitrary final state within finite time.",
  "Controllability" = "The intrinsic difficulty of controlling an ecological community. It is measured by the relative size of the minimum driver-node set, $n_D$. It also indicates the extent to which network structure can be harnessed for network control.", 
  "Minimum driver-node set" = "One of the sets of species whose abundances need to be directly managed in order to achieve full control of the community. The minimum driver-node sets can be obtained by finding all maximum matchings in a network.",
  "Maximum matching" = "A matching is a set of links that do not share any common start or end nodes; the largest possible matching is called a maximum matching.",
  "Control configuration" = "One of the species combinations with which is possible to achieve network control. Optimal control configurations are given by the minimum driver-node sets.", 
  "Control capacity" = "The relative frequency \\(\\phi\\) which with a species is part of the optimal control configurations of a network.", 
  "Critical species" = "A species with a maximal control capacity \\(\\phi=1\\).",
  "Superior node" = "A species is a superior node if it can internally affect the abundance of other species in the network. Superior nodes make up the chains that propagate the control signals through the network.")
dplyr::data_frame(rows = c(rbind(names(defs), unlist(defs))), dummy2 = "") %>%
  dplyr::mutate(rows = kableExtra::cell_spec(rows, "latex", bold = T:F, escape = F)) %>%
  knitr::kable("latex", 
               booktabs = T, 
               col.names = NULL,
               caption = "Glossary", 
               escape = F, 
               linesep = c('', '\\addlinespace')) %>% 
  kableExtra::kable_styling(font_size = 10) %>%
  kableExtra::add_indent(seq(2, length(defs)*2, by = 2)) %>%
  kableExtra::column_spec(1, width = paste0(fig_sizes()$two_column_width * 0.9, "in"))
```

