--- 
title: "The resilience of ecological networks"
author: "Fernando Cagua"
output:
  bookdown::pdf_book:
    template: latex-components/latex-template.tex
    keep_tex: yes
    citation_package: biblatex
    pandoc_args: --top-level-division=chapter
link-citations: yes
site: bookdown::bookdown_site
---

```{r, include=FALSE}
# Load required packages
library(magrittr)
library(ggplot2)
library(showtext)
# Load functions
knitr::opts_chunk$set(out.width = '\\textwidth', 
                      fig.width = fig_sizes()$two_column_width,
                      fig.align = 'center',
                      dpi = 300,
                      echo = FALSE,
                      message = FALSE, 
                      warning = FALSE, 
                      cache = FALSE, 
                      fig.showtext = TRUE)
options(knitr.kable.NA = '')
```

```{r load-dependences, include = FALSE, cache = FALSE}

# latex template 
file_in("latex-components/latex-template.tex")
file_in("latex-components/config.tex")

# latex style
file_in("latex-components/style/classicthesis.sty")
file_in("latex-components/style/classicthesis-arsclassica.sty")

# Template components
file_in("latex-components/front-back-matter/acknowledgments.tex")
file_in("latex-components/front-back-matter/bibliography.tex")
file_in("latex-components/front-back-matter/colophon.tex")
file_in("latex-components/front-back-matter/contents.tex")
file_in("latex-components/front-back-matter/declaration.tex")
file_in("latex-components/front-back-matter/dedication.tex")
file_in("latex-components/front-back-matter/display-listings.tex")
file_in("latex-components/front-back-matter/glossary-defs.tex")
file_in("latex-components/front-back-matter/glossary.tex")
file_in("latex-components/front-back-matter/little-dirty-title-page.tex")
file_in("latex-components/front-back-matter/preface.tex")
file_in("latex-components/front-back-matter/publications.tex")
# file_in("latex-components/front-back-matter/resumen.tex")
# file_in("latex-components/front-back-matter/summary.tex")
file_in("latex-components/front-back-matter/table-of-contents.tex")
file_in("latex-components/front-back-matter/title-back.tex")
file_in("latex-components/front-back-matter/title-page.tex")

# other chapters
knitr_in("chapters/introduction.Rmd")
knitr_in("chapters/sdm-networks.Rmd")
knitr_in("chapters/driver-species.Rmd")
knitr_in("chapters/trade-off.Rmd")
knitr_in("chapters/conclusion.Rmd")
knitr_in("chapters/coevolution.Rmd")

# bibliography
file_in("bibliography/phd-literature.bib")
```



